### ISSUE TITLE
runtime list index issue

### ISSUE THREAD

**Issue by apurkaya-nrel** [NREL/dgen#27]
Issue overview
--------------
Hello, 
I am attempting to run dGen for the first time on my laptop (Mac OSX Monterrey with apple silicon). I followed the instructions for setting up everything on the repo page -- installing all the tools including docker, PgAdmin, dg3n conda env -- to run a simple state (DC) scenario. All the docker commands in the instructions to set up and connect/load to pgadmin went fine and everything else until the run step. I edited the 1) input_scenarios/my_scenario.xslm, where I changed the scenario name and region; 2) changed python/pg_params_connect.json where the dbname:"dgen_db", host:"localhost" were set and with other parameters unchanged ; 3) did not change anything in python/settings.py since the default values for "role" were already set in pythons/config.py. 

Then when I ran "$ python dgen_model.py", I get errors shown in the attached log file. Unless there a limit to the characters in the hard coded path, I do not understand what list is out of index.

Thanks for your help.

### Details
Some additional details for this issue (if relevant): Mac
 - Platform (Operating system, version) macOS Monterrey (12.5.1)
 - Version of dGen (cloned the main branch 10/19/2022)
[dg_model.log](https://github.com/NREL/dgen/files/9825260/dg_model.log)

**Comment by apurkaya-nrel** [comment]
issue resolved. the input scenario file name needs to be same as the original reference file in excel

**Comment by michaelavs** [comment]
Hi @jboggs326,
I'm new with dGen, but I believe I can maybe help with an explanation of the error and the solution provided above. So looking at the full traceback of the error, there are three files provided: `settings.py` (line 508), `dgen_model.py` (line 75), and `data_functions.py` (line 157). The line I believe to be responsible for the error is the one in `data_funstions.py` which is `scen_suffix = os.path.split(scenario_list[0])[1].split('_')[2].rstrip('.xlsm')`. When the code is running, if the file name is not in a correct format, the split function can throw an error. An example of an incorrect format that could cause an error is if the file does not have a `_` in the correct position the function is looking for, or if the file does not end with '.xlsm' as that is what it is expecting to find. When this happens, the function will throw an `IndexError` because the there is no matching element in that index. 

This [Stack Overflow](https://stackoverflow.com/questions/24100285/list-index-out-of-range-with-split) may provide a little bit more insight on this topic as well. Hopefully this helps, but I can definitely try to answer any further questions if needed!
