### ISSUE TITLE
national agent file fails on national DB

### ISSUE THREAD

**Issue by T-Man-Stan** [NREL/dgen#9]
national agent file fails to run fully on the national level database. Individual states seem to work fine.

**Comment by ajgong** [comment]
When using the agent file "agent_df_base_res_national_revised.pkl" and the national dgen_db.sql backup, an issue occurs because building ID 580 is listed as being in state LA in the agent file and MO in the database file. Specifically, in financial_functions.py, the load_profile_df may be returned as an empty df because the sql lookup returns nothing, resulting in an error when assigning the load profile data to the pv dataframe. The files were downloaded on 1/26

**Comment by T-Man-Stan** [comment]
@ajgong This is a known issue within the agent file and has been resolved, however, we're waiting for the agent file to be updated in the OEDI data catalog. For now I've put this agent file in https://github.com/NREL/dgen/tree/master/dgen_os/agents.

**Comment by T-Man-Stan** [comment]
This has since been resolved. The new national residential agent file has been uploaded to OEDI and is called: agent_df_base_res_national_revised_v2.pkl
